### ISSUE TITLE
Page does not render as HTML

### ISSUE THREAD

**Issue by bbarker** [vitaliis/ScalaJS-Mill-WebApp#3]
I've tried this with a few different browsers and versions of dependencies, but the result is always the same:

![image](https://user-images.githubusercontent.com/916366/115995068-c2b9a580-a5a7-11eb-9f4b-b370285483f7.png)

I'm not very familiar with Cask, and assume it is related to a header issue there. But, I suppose it could be a scalatags issue as well.

**Comment by vitaliis** [comment]
I found where the problem was. There are actually 2.
1. `.render` was not necessary.
2. And this first problem resulted in "Content-Type: text/plain" header.

Fixed in 81490f4.
Added couple of headers as an example of its usage in cask.
